name: _build

jobs:
  build:
    runs-on: ubuntu-latest
    # grants permissions for the artifact to be uploaded
    permissions:
      contents: read
      packages: write
    
    
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acces it and clones the repo
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: |
          pwd
          mvn -B clean package --file pom.xml
          
      - uses: actions/upload-artifact@v4
        with:
          name: veracode-artifact
          path: /home/runner/work/vulnado/vulnado/target/vulnado-0.0.1-SNAPSHOT.jar
          if-no-files-found: error
